# Generated by Django 5.2.8 on 2025-12-01 14:26

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('request_body', models.BinaryField(null=True)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'key'], name='orders_app__tenant__05de89_idx')],
                'unique_together': {('tenant_id', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('total_cents', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', '-created_at', '-id'], name='orders_tenant_created_id_idx')],
            },
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('order_id', models.UUIDField()),
                ('tenant_id', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='orders_app__tenant__6d40ea_idx')],
            },
        ),
    ]
